### ISSUE TITLE
cannot import name 'FlaxWhisperPipline' from partially initialized module 'whisper_jax' (most likely due to a circular import) ..

### ISSUE THREAD

**Issue by alcarazolabs** [sanchit-gandhi/whisper-jax#164]
Hi dear, I just installed whisper-jax successfully in my device after some sticks, however when I tried to run the code I got this error:

```
(.myenv) orin@ubuntu:~/Documents/whisper/whisperjax$ python jax.py 
Traceback (most recent call last):
  File "/home/orin/Documents/whisper/whisperjax/jax.py", line 1, in <module>
    from whisper_jax import FlaxWhisperPipline
  File "/home/orin/Documents/whisper/whisperjax/.myenv/lib/python3.9/site-packages/whisper_jax/__init__.py", line 18, in <module>
    from .modeling_flax_whisper import FlaxWhisperForConditionalGeneration
  File "/home/orin/Documents/whisper/whisperjax/.myenv/lib/python3.9/site-packages/whisper_jax/modeling_flax_whisper.py", line 21, in <module>
    import flax.linen as nn
  File "/home/orin/Documents/whisper/whisperjax/.myenv/lib/python3.9/site-packages/flax/__init__.py", line 19, in <module>
    from .configurations import (
  File "/home/orin/Documents/whisper/whisperjax/.myenv/lib/python3.9/site-packages/flax/configurations.py", line 24, in <module>
    from jax import config as jax_config
  File "/home/orin/Documents/whisper/whisperjax/jax.py", line 1, in <module>
    from whisper_jax import FlaxWhisperPipline
ImportError: cannot import name 'FlaxWhisperPipline' from partially initialized module 'whisper_jax' (most likely due to a circular import) (/home/orin/Documents/whisper/whisperjax/.myenv/lib/python3.9/site-packages/whisper_jax/__init__.py)
```

what does mean this:

`cannot import name 'FlaxWhisperPipline' from partially initialized module 'whisper_jax' (most likely due to a circular import) (/home/orin/Documents/whisper/whisperjax/.myenv/lib/python3.9/site-packages/whisper_jax/__init__.py)`

I just imported this class: `from whisper_jax import FlaxWhisperPipline` however it throwed that error.

How I can fix this problem in my device.

Thanks in advance.

**Comment by alcarazolabs** [comment]
I fixed this issue, the problem was that my test script was called jax.py I moved it to testjax.py and now worked.

**Comment by charmeem** [comment]
It worked for me as well but wondering why changing the name is so critical!
