### ISSUE TITLE
ValueError: ffmpeg was not found but is required to load audio files from filename

### ISSUE THREAD

**Issue by mriamnobody** [sanchit-gandhi/whisper-jax#27]
I executed the command `python app.py` and provided a YouTube video link through the web interface, but received the following error message:
```
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\transformers\pipelines\audio_utils.py", line 34, in ffmpeg_read
    with subprocess.Popen(ffmpeg_command, stdin=subprocess.PIPE, stdout=subprocess.PIPE) as ffmpeg_process:
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\app\app.py", line 183, in transcribe_youtube
    inputs = ffmpeg_read(inputs, processor.feature_extractor.sampling_rate)
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\transformers\pipelines\audio_utils.py", line 37, in ffmpeg_read
    raise ValueError("ffmpeg was not found but is required to load audio files from filename") from error
ValueError: ffmpeg was not found but is required to load audio files from filename
```

I have added `ffmpeg` to the path as well as I have also installed `ffmpeg-python` but still the same issue.

In case I select the `Microphone` tab and record the audio and click submit I get the following error:

```
C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\processing_utils.py", line 138, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\blocks.py", line 1300, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\blocks.py", line 1148, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\components.py", line 2425, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "C:\Users\rosha\Downloads\Compressed\whisper-jax-main\whisper\lib\site-packages\gradio\processing_utils.py", line 148, in audio_from_file
    raise RuntimeError(msg) from e
RuntimeError: Cannot load audio from file: `ffprobe` not found. Please install `ffmpeg` in your system to use non-WAV audio file formats and make sure `ffprobe` is in your PATH.
```

**Comment by sgreenb** [comment]
I don't think ffmpeg-python is the same as ffmpeg. Get ffmpeg. You're going to have an easier time getting this to work in WSL on Windows, in which case you can use 
```
sudo apt update && sudo apt upgrade
sudo apt install ffmpeg
```
Otherwise you'll have to download the ffmpeg.7z file and add it to your path.

**Comment by sanchit-gandhi** [comment]
Indeed, as @sgreenb has mentioned we require the (non-Python) package [ffmpeg](https://ffmpeg.org)
