### ISSUE TITLE
[Bug]Invalid URL 'None': No schema supplied

### ISSUE THREAD

**Issue by mriamnobody** [sanchit-gandhi/whisper-jax#28]
This issue occurs when I provide a Youtube link. I'm on Windows 11 (Python 3.10.6) using command `python app.py`
```
Traceback (most recent call last):
  File "/home/ethan/.local/lib/python3.10/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ethan/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/home/ethan/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ethan/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ethan/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ethan/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/c/Users/rosha/whisper-jax/app/app.py", line 185, in transcribe_youtube
    text, runtime = tqdm_generate(inputs, task=task, return_timestamps=return_timestamps, progress=progress)
  File "/mnt/c/Users/rosha/whisper-jax/app/app.py", line 126, in tqdm_generate
    model_outputs.append(forward(batch, task=task, return_timestamps=return_timestamps))
  File "/mnt/c/Users/rosha/whisper-jax/app/app.py", line 69, in forward
    outputs = chunked_query(
  File "/mnt/c/Users/rosha/whisper-jax/app/app.py", line 62, in chunked_query
    response = requests.post(API_URL_FROM_FEATURES, json=payload)
  File "/home/ethan/.local/lib/python3.10/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ethan/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ethan/.local/lib/python3.10/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/ethan/.local/lib/python3.10/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/ethan/.local/lib/python3.10/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/ethan/.local/lib/python3.10/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

```

**Comment by sanchit-gandhi** [comment]
Hey @mriamnobody, you need to specify the `API_URL` for this to work when you launch the app. Please refer to the instructions for creating an endpoint: https://github.com/sanchit-gandhi/whisper-jax#creating-an-endpoint
