### ISSUE TITLE
Web App does not start

### ISSUE THREAD

**Issue by achaiah** [sanchit-gandhi/whisper-jax#60]
Seems like there is an issue with the web UI. It fails with the following message:

```
user@86ca:/workspace/whisper-jax# python app/app.py
Initialized persistent compilation cache at ./jax_cache
Downloading (…)neration_config.json: 100%
2023-04-28 21:06:08;INFO;compiling forward call...
Traceback (most recent call last):
  File "app/app.py", line 85, in <module>
    random_timestamps = pipeline.forward(random_inputs, batch_size=BATCH_SIZE, return_timestamps=True)
  File "/workspace/whisper-jax/whisper_jax/pipeline.py", line 403, in forward
    input_features = model_inputs.pop("input_features")
KeyError: 'input_features'
Exception ignored in: <function Pool.__del__ at 0x7f260fee0f70>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

**Comment by sanchit-gandhi** [comment]
Should be fixed on main!
